<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#마지막-체크" data-toc-modified-id="마지막-체크-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>마지막 체크</a></span></li></ul></div>

In [192]:
import pandas as pd # 데이터 전처리를 위한 라이브러리
import numpy as np # 행렬 처리를 위한 라이브러리

In [137]:
# Define Number and Level
levels = ['광역시도' ,'시군구' ,'읍면동']
level = '광역시도'
num = 800 # 제한하는 값이 따로 있는지
filename = '19년 7월 인구현황(8월작성)'

# levels에서 선택된 level은 제외
levels.remove(level)

In [138]:
# Load Data
df = pd.read_excel("데이터/{}.xlsx".format(filename), sheet_name=1)
df = df[df.구분==level]
df = df.drop(levels, axis=1)

In [139]:
df.head()

구분   광역시도  남 19-29세   남 30대   남 40대   남 50대  남 60세 이상  여 19-29세  \
0    광역시도  서울특별시    772628  763229  778853  758124    967381    796778   
450  광역시도  부산광역시    250679  226701  261279  284872    402061    227315   
673  광역시도  대구광역시    193178  160362  195810  211316    242479    165759   
823  광역시도  인천광역시    232021  219865  250219  259402    265413    212114   
991  광역시도  광주광역시    119834   99414  121881  115456    124248    109205   

      여 30대   여 40대   여 50대  여 60세이상     남 합계     여 합계       총계  
0    763233  791426  790462  1170959  4040215  4312858  8353073  
450  217102  258866  304155   494673  1425592  1502111  2927703  
673  151258  200962  220150   305662  1003145  1043791  2046936  
823  206515  240572  258497   314533  1226920  1232231  2459151  
991   97011  123592  117854   156606   580833   604268  1185101

In [140]:
# Define Features
male_cols = ['남 19-29세', '남 30대', '남 40대', '남 50대', '남 60세 이상']
female_cols = ['여 19-29세', '여 30대', '여 40대', '여 50대', '여 60세이상']
total_cols = male_cols + female_cols

In [141]:
# Total Population
total_pop = df[total_cols].sum().sum()
print('전체 인구수: ',total_pop)

전체 인구수:  43222320


In [142]:
# 2단계 반올림 전
before_df = df.copy()
# 각 셀값을 전체 인구로 나누고 정해진 값으로 곱ㅎ
before_df[total_cols] = (df[total_cols] / total_pop) * num 
# 남/여/총 합계 구하기
before_df['남 합계'] = before_df[male_cols].sum(axis=1)
before_df['여 합계'] = before_df[female_cols].sum(axis=1)
before_df['총계'] = before_df[['남 합계' ,'여 합계']].sum(axis=1)
# 2단계 남여 각각 합계의 반올림
before_sex_sum = before_df[['남 합계' ,'여 합계']].sum().round()

In [143]:
before_df.head()

구분   광역시도   남 19-29세      남 30대      남 40대      남 50대   남 60세 이상  \
0    광역시도  서울특별시  14.300537  14.126572  14.415756  14.032083  17.905212   
450  광역시도  부산광역시   4.639806   4.195999   4.836001   5.272683   7.441729   
673  광역시도  대구광역시   3.575523   2.968133   3.624239   3.911238   4.488033   
823  광역시도  인천광역시   4.294466   4.069472   4.631292   4.801260   4.912517   
991  광역시도  광주광역시   2.218002   1.840049   2.255890   2.136970   2.299701   

      여 19-29세      여 30대      여 40대      여 50대    여 60세이상       남 합계  \
0    14.747529  14.126646  14.648469  14.630626  21.673228  74.780160   
450   4.207363   4.018331   4.791339   5.629591   9.155881  26.386219   
673   3.068026   2.799628   3.719597   4.074747   5.657484  18.567166   
823   3.926009   3.822377   4.452736   4.784509   5.821677  22.709008   
991   2.021270   1.795572   2.287559   2.181354   2.898613  10.750612   

          여 합계          총계  
0    79.826497  154.606657  
450  27.802506   54.188725  
673  19.319481   37.886647  
823  22.807309   45.516317  
991  11.184370   21.934982

In [144]:
before_sex_sum

남 합계    397.0
여 합계    403.0
dtype: float64

In [194]:
# 3단계 반올림 후
after_df = df.copy()
# 각 셀값을 전체 인구로 나누고 정해진 값으로 곱ㅎ
after_df[total_cols] = (df[total_cols] / total_pop) * num 
# 각 셀을 반올림
after_df[total_cols] = after_df[total_cols].round() 
# 남/여/총 합계 구하기
after_df['남 합계'] = after_df[male_cols].sum(axis=1)
after_df['여 합계'] = after_df[female_cols].sum(axis=1)
after_df['총계'] = after_df[['남 합계' ,'여 합계']].sum(axis=1)
# 3단계 남여 각각 합계의 반올림
after_sex_sum = after_df[['남 합계' ,'여 합계']].sum()

In [195]:
after_df.head()

구분   광역시도  남 19-29세  남 30대  남 40대  남 50대  남 60세 이상  여 19-29세  여 30대  \
0    광역시도  서울특별시      14.0   14.0   14.0   14.0      18.0      15.0   14.0   
450  광역시도  부산광역시       5.0    4.0    5.0    5.0       7.0       4.0    4.0   
673  광역시도  대구광역시       4.0    3.0    4.0    4.0       4.0       3.0    3.0   
823  광역시도  인천광역시       4.0    4.0    5.0    5.0       5.0       4.0    4.0   
991  광역시도  광주광역시       2.0    2.0    2.0    2.0       2.0       2.0    2.0   

     여 40대  여 50대  여 60세이상  남 합계  여 합계     총계  
0     15.0   15.0     22.0  74.0  81.0  155.0  
450    5.0    6.0      9.0  26.0  28.0   54.0  
673    4.0    4.0      6.0  19.0  20.0   39.0  
823    4.0    5.0      6.0  23.0  23.0   46.0  
991    2.0    2.0      3.0  10.0  11.0   21.0

In [147]:
after_sex_sum

남 합계    393.0
여 합계    403.0
dtype: float64

In [148]:
# 2,3단계 남여 합계의 차이
'''
차이는 세 가지 경우로 나뉜다: 남여 각각 차이가 1. 0이거나 / 2. 0보다 크거나 / 3. 0보다 작거나 
1. 0인 경우는 추가적인 일 없이 표 완성
2. 만약 차이가 0보다 큰 경우 : xx.5 보다 작고 xx.5에 가장 가까운 값인 반올림 값에 + 1 
- Why? 반올림하여 내림이 된 값 중 가장 올림에 가까운 값에 1을 더하는 것이 이상적이기 때문
    ex) 2.49999 -> round(2.49999) + 1
3. 만약 차이가 0보다 작은 경우 : xx.5 이상이고 xx.5에 가장 가까운 값인 반올림 값에 - 1
- Why? 반올림하여 올림이 된 값 중 가장 내림에 가까운 값에 1을 빼는 것이 이상적이기 때문
    ex) 2.50001 -> round(2.50001) - 1
'''
sex_diff = before_sex_sum - after_sex_sum

In [149]:
sex_diff

남 합계    4.0
여 합계    0.0
dtype: float64

In [150]:
# 성별 합계 차이를 매꾸는 단계
sex_cols_lst = [male_cols, female_cols]
sex_idx = ['남 합계' ,'여 합계']
print('sex_cols_lst: ',sex_cols_lst)
print('sex_cols: ',sex_idx)

sex_cols_lst:  [['남 19-29세', '남 30대', '남 40대', '남 50대', '남 60세 이상'], ['여 19-29세', '여 30대', '여 40대', '여 50대', '여 60세이상']]
sex_cols:  ['남 합계', '여 합계']


In [151]:
# 차이가 0보다 큰 경우
'''
1단계: 2단계 반올림 전 값을 모두 내림 한 후 0.5를 더 한다.
2단계: 1번에서 한 값과 2단계 반올림 전 값을 뺀다.
3단계: 음수로 나오는 값은 모두 1로 변환. 1이 가장 큰 값이기 때문.
ex) 13.45 -> 13 으로 내림 후 (13 + 0.5) - 13.45 = 0.05
'''
temp = (before_df[sex_cols_lst[0]].astype(int) + 0.5) - before_df[sex_cols_lst[0]] # 1,2번
temp = temp[temp >0].fillna(1) # 3번
v = 1

In [207]:
# 2단계 값
before_df[sex_cols_lst[0]].head()

남 19-29세      남 30대      남 40대      남 50대   남 60세 이상
0    14.300537  14.126572  14.415756  14.032083  17.905212
450   4.639806   4.195999   4.836001   5.272683   7.441729
673   3.575523   2.968133   3.624239   3.911238   4.488033
823   4.294466   4.069472   4.631292   4.801260   4.912517
991   2.218002   1.840049   2.255890   2.136970   2.299701

In [153]:
# 전체 소수점을 내림한다.
before_df[sex_cols_lst[0]].astype(int).head()

남 19-29세  남 30대  남 40대  남 50대  남 60세 이상
0          14     14     14     14        17
450         4      4      4      5         7
673         3      2      3      3         4
823         4      4      4      4         4
991         2      1      2      2         2

In [154]:
# 내림된 값에다 0.5를 더한다.
(before_df[sex_cols_lst[0]].astype(int) + 0.5).head()

남 19-29세  남 30대  남 40대  남 50대  남 60세 이상
0        14.5   14.5   14.5   14.5      17.5
450       4.5    4.5    4.5    5.5       7.5
673       3.5    2.5    3.5    3.5       4.5
823       4.5    4.5    4.5    4.5       4.5
991       2.5    1.5    2.5    2.5       2.5

In [155]:
# 0.5를 더한 값에 2단계를 뺀다
test = (before_df[sex_cols_lst[0]].astype(int) + 0.5) - before_df[sex_cols_lst[0]]
test.head()

남 19-29세     남 30대     남 40대     남 50대  남 60세 이상
0    0.199463  0.373428  0.084244  0.467917 -0.405212
450 -0.139806  0.304001 -0.336001  0.227317  0.058271
673 -0.075523 -0.468133 -0.124239 -0.411238  0.011967
823  0.205534  0.430528 -0.131292 -0.301260 -0.412517
991  0.281998 -0.340049  0.244110  0.363030  0.200299

In [156]:
# 0보다 큰 값만 사용한다.
test[test>0].head()

남 19-29세     남 30대     남 40대     남 50대  남 60세 이상
0    0.199463  0.373428  0.084244  0.467917       NaN
450       NaN  0.304001       NaN  0.227317  0.058271
673       NaN       NaN       NaN       NaN  0.011967
823  0.205534  0.430528       NaN       NaN       NaN
991  0.281998       NaN  0.244110  0.363030  0.200299

In [157]:
# NaN은 Not a Number의 약자. 결측치라는 얘기. 
# 결측치는 모두 1로 처리 가장 크기 때문
test2 = test[test>0].fillna(1)
test2.head()

남 19-29세     남 30대     남 40대     남 50대  남 60세 이상
0    0.199463  0.373428  0.084244  0.467917  1.000000
450  1.000000  0.304001  1.000000  0.227317  0.058271
673  1.000000  1.000000  1.000000  1.000000  0.011967
823  0.205534  0.430528  1.000000  1.000000  1.000000
991  0.281998  1.000000  0.244110  0.363030  0.200299

In [196]:
# 실제합계와의 차이: 절대값을 통해서 음수를 변환하고 정수로 타입을 변환
cnt = int(abs(sex_diff.loc[sex_idx[0]]))
cnt

4

In [159]:
# 1행으로 변환
test3 = test2.values
test3.ravel()

array([0.19946269, 0.37342836, 0.08424444, 0.46791658, 1.        ,
       1.        , 0.30400127, 1.        , 0.22731681, 0.05827082,
       1.        , 1.        , 1.        , 1.        , 0.01196697,
       0.20553362, 0.43052849, 1.        , 1.        , 1.        ,
       0.28199782, 1.        , 0.24410999, 0.36303003, 0.20029929,
       0.2249162 , 1.        , 0.2389645 , 0.24742309, 0.03107191,
       1.        , 1.        , 1.        , 0.49444361, 1.        ,
       0.13642859, 1.        , 1.        , 0.1064811 , 0.11049754,
       1.        , 0.13337831, 0.02374421, 1.        , 1.        ,
       0.44513575, 1.        , 0.29971089, 1.        , 1.        ,
       0.25408631, 1.        , 0.14919606, 1.        , 0.24460788,
       1.        , 1.        , 0.25038267, 0.17917872, 0.12059603,
       0.13405574, 1.        , 1.        , 1.        , 0.43833927,
       0.20738822, 1.        , 1.        , 0.36058499, 0.01054178,
       0.11908014, 0.43123368, 1.        , 0.03989698, 0.33059

In [160]:
# 작은 값을 기준으로 각 값들의 위치를 표시하여 정렬
np.argsort(test3.ravel())

array([69, 14, 42, 29, 73, 79,  9,  2, 75, 38, 39, 70, 59, 41, 60, 35, 52,
       58,  0, 24, 15, 65, 25,  8, 27, 22, 54, 28, 57, 50, 20, 77, 47,  6,
       84, 74, 76, 68, 23,  1, 82, 16, 71, 83, 64, 45,  3, 33, 61, 62, 63,
       80, 66, 67,  7, 72, 78,  5, 81,  4, 19, 56, 21, 26, 17, 30, 31, 32,
       34, 36, 37, 13, 40, 12, 43, 44, 46, 48, 49, 18, 11, 53, 55, 10, 51],
      dtype=int64)

In [161]:
# 상위 n개 선택
np.argsort(test3.ravel())[:cnt]

array([69, 14, 42, 29], dtype=int64)

In [205]:
row_col

(array([13,  2,  8,  5], dtype=int64), array([4, 4, 2, 4], dtype=int64))

In [162]:
# unravel_index라는 함수를 통해서 각 위치 좌표를 추출
row_col = np.unravel_index(np.argsort(test3.ravel())[:cnt], test3.shape)
rows = row_col[0]
cols = row_col[1]
print('rows: ',rows)
print('cols: ',cols)

rows:  [13  2  8  5]
cols:  [4 4 2 4]


In [179]:
# 남자들 인구만 추출
temp = before_df[sex_cols_lst[0]].copy() 
temp.head()

남 19-29세      남 30대      남 40대      남 50대   남 60세 이상
0    14.300537  14.126572  14.415756  14.032083  17.905212
450   4.639806   4.195999   4.836001   5.272683   7.441729
673   3.575523   2.968133   3.624239   3.911238   4.488033
823   4.294466   4.069472   4.631292   4.801260   4.912517
991   2.218002   1.840049   2.255890   2.136970   2.299701

In [180]:
# 아슬아슬한애가 누구인지 확인
value = temp.iloc[rows[0] ,cols[0]]
print('{}의 {}: {}'.format(df[level].iloc[rows[0]], sex_cols_lst[0][cols[0]], value))

전라남도의 남 60세 이상: 4.489458224361857


In [186]:
# 아슬아슬한 애들에게 1만큼 더하기
temp = after_df[sex_cols_lst[0]].copy()
print('1만큼 더해진 값: ',temp.iloc[rows[0] ,cols[0]] + v)

1만큼 더해진 값:  5.0


In [208]:
# 3단계 데이터프레임에 전라남도의 남 60세 이상에 1을 더해줌
temp.iloc[rows[0] ,cols[0]] = temp.iloc[rows[0] ,cols[0]] + v
temp.head(14)

남 19-29세  남 30대  남 40대  남 50대  남 60세 이상
0         14.0   14.0   14.0   14.0      18.0
450        5.0    4.0    5.0    5.0       7.0
673        4.0    3.0    4.0    4.0       5.0
823        4.0    4.0    5.0    5.0       5.0
991        2.0    2.0    2.0    2.0       2.0
1092       2.0    2.0    2.0    2.0       3.0
1177       2.0    2.0    2.0    2.0       2.0
1239       0.0    1.0    1.0    0.0       0.0
1259      19.0   18.0   22.0   21.0      21.0
1847       2.0    2.0    2.0    3.0       4.0
2060       2.0    2.0    2.0    3.0       3.0
2229       3.0    3.0    3.0    3.0       4.0
2456       2.0    2.0    3.0    3.0       4.0
2716       2.0    2.0    3.0    3.0       6.0

In [189]:
# 위에 내용을 일반화
for r in range(len(rows)):
    temp = before_df[sex_cols_lst[0]].copy()
    value = temp.iloc[rows[r] ,cols[r]]
    print('{}의 {}: {}'.format(df[level].iloc[rows[r]], sex_cols_lst[0][cols[r]], value))
    temp = after_df[sex_cols_lst[0]].copy()
    temp.iloc[rows[r] ,cols[r]] = temp.iloc[rows[r] ,cols[r]] + v
    after_df[sex_cols_lst[0]] = temp
print()

전라남도의 남 60세 이상: 4.489458224361857
대구광역시의 남 60세 이상: 4.48803303478388
경기도의 남 40대: 21.47625578636223
대전광역시의 남 60세 이상: 2.4689280908567612



In [190]:
# 부족한 부분이 채워졌으면 합계 계산
after_df['남 합계'] = after_df[male_cols].sum(axis=1)
after_df['여 합계'] = after_df[female_cols].sum(axis=1)
after_df['총계'] = after_df[['남 합계','여 합계']].sum(axis=1)
after_df[['남 합계','여 합계']].sum()

남 합계    397.0
여 합계    403.0
dtype: float64

In [191]:
after_df

구분     광역시도  남 19-29세  남 30대  남 40대  남 50대  남 60세 이상  여 19-29세  여 30대  \
0     광역시도    서울특별시      14.0   14.0   14.0   14.0      18.0      15.0   14.0   
450   광역시도    부산광역시       5.0    4.0    5.0    5.0       7.0       4.0    4.0   
673   광역시도    대구광역시       4.0    3.0    4.0    4.0       5.0       3.0    3.0   
823   광역시도    인천광역시       4.0    4.0    5.0    5.0       5.0       4.0    4.0   
991   광역시도    광주광역시       2.0    2.0    2.0    2.0       2.0       2.0    2.0   
1092  광역시도    대전광역시       2.0    2.0    2.0    2.0       3.0       2.0    2.0   
1177  광역시도    울산광역시       2.0    2.0    2.0    2.0       2.0       1.0    1.0   
1239  광역시도  세종특별자치시       0.0    1.0    1.0    0.0       0.0       0.0    1.0   
1259  광역시도      경기도      19.0   18.0   22.0   21.0      21.0      17.0   17.0   
1847  광역시도      강원도       2.0    2.0    2.0    3.0       4.0       2.0    2.0   
2060  광역시도     충청북도       2.0    2.0    2.0    3.0       3.0       2.0    2.0   
2229  광역시도     충청남도       3.0    3.0    3.0    3.0       4.0       2.0    2.0   
2456  광역시도     전라북도       2.0    2.0    3.0    3.0       4.0       2.0    2.0   
2716  광역시도     전라남도       2.0    2.0    3.0    3.0       5.0       2.0    2.0   
3062  광역시도     경상북도       3.0    3.0    4.0    4.0       6.0       3.0    3.0   
3433  광역시도     경상남도       4.0    4.0    5.0    6.0       6.0       4.0    4.0   
3770  광역시도  제주특별자치도       1.0    1.0    1.0    1.0       1.0       1.0    1.0   

      여 40대  여 50대  여 60세이상   남 합계  여 합계     총계  
0      15.0   15.0     22.0   74.0  81.0  155.0  
450     5.0    6.0      9.0   26.0  28.0   54.0  
673     4.0    4.0      6.0   20.0  20.0   40.0  
823     4.0    5.0      6.0   23.0  23.0   46.0  
991     2.0    2.0      3.0   10.0  11.0   21.0  
1092    2.0    2.0      3.0   11.0  11.0   22.0  
1177    2.0    2.0      2.0   10.0   8.0   18.0  
1239    1.0    0.0      0.0    2.0   2.0    4.0  
1259   21.0   20.0     24.0  101.0  99.0  200.0  
1847    2.0    2.0      4.0   13.0  12.0   25.0  
2060    2.0    2.0      4.0   12.0  12.0   24.0  
2229    3.0    3.0      5.0   16.0  15.0   31.0  
2456    2.0    3.0      5.0   14.0  14.0   28.0  
2716    2.0    3.0      6.0   15.0  15.0   30.0  
3062    3.0    4.0      8.0   20.0  21.0   41.0  
3433    5.0    5.0      8.0   25.0  26.0   51.0  
3770    1.0    1.0      1.0    5.0   5.0   10.0